### ISSUE TITLE
LIMS integration

### ISSUE THREAD

**Issue by NileGraddis** [AllenInstitute/sweep_qc_tool#43]
Users should be able to QC datasets in LIMS using the sweep QC tool. This specifically means:
1. users can select an experiment from LIMS and load it into sweep QC tool
2. if a user is QCing an experiment in LIMS, they can post the results of their QC back to LIMS.

tasks (may change with completion of design):
- [ ] #40 design LIMS integration & determine required LIMS work
- [ ] implement local NWB caching
- [ ] implement LIMS credential handling
- [ ] implement NWB fetching
- [ ] implement QC result posting to LIMS
- [ ] implement LIMS ipfx version vs. QC tool version check

**Comment by kasbaker** [comment]
IVSCC would like to be able to load experiments from LIMS by inputting a specimen ID. I have some code that does this. This issue is related to https://github.com/AllenInstitute/sweep_qc_tool/issues/51
